spring.application.name=controleProjetoIntegrador


#Localhost 
spring.datasource.url=jdbc:postgresql://dpg-d4eqsdvpm1nc7390t14g-a.oregon-postgres.render.com:5432/controle_projeto_integrador
spring.datasource.username=controle_projeto_integrador_user
spring.datasource.password=97pZVuRSpDnDzmABupzNPvEblg8eL0L9
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver


#Swagger
springdoc.api-docs.path=v3/api-docs
springdoc.swagger-ui.path=/controle-projeto-integrador/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true